services:
  kong:
    image: kong:3.8
    container_name: kong
    ports:
      - "8000:8000"   # Porta para serviços (HTTP)
      - "8443:8443"   # Porta para serviços (HTTPS)
      - "8001:8001"   # Porta para administração (HTTP)
      - "8444:8444"   # Porta para administração (HTTPS)
    environment:
      KONG_DATABASE: "off" 
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml  # arquivo de configuração
  
  pedido1:
    build:
      context: ./pedido_service
    image: pedido_service:latest
    container_name: pedido1
    depends_on:
      - kong
      
  pagamento1:
    build:
      context: ./pagamento_service
    image: pagamento_service:latest
    container_name: pagamento1
    depends_on:
      - kong

  user1:
    build:
      context: ./users_service
    image: users_service:latest
    container_name: user1
    depends_on:
      - kong